packages:
  - packages/*
  - test

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/types': ^19.8.1
    '@lerna-lite/cli': ^4.7.2
    '@lerna-lite/publish': ^4.7.2
    '@types/confusing-browser-globals': ^1.0.3
    '@types/eslint': ^9.6.1
    '@types/node': ^24.3.0
    eslint: ^9.34.0
    husky: ^9.1.7
    lint-staged: ^16.1.5
    prettier: ^3.6.2
    rimraf: ^6.0.1
    sort-package-json: ^3.4.0
    tsdown: ^0.14.2
    tsx: ^4.20.5
    typescript: ^5.9.2
  peer:
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-vue: ^10.4.0
    vue-eslint-parser: ^10.2.0
  prod:
    '@typescript-eslint/eslint-plugin': ^8.41.0
    '@typescript-eslint/parser': ^8.41.0
    '@typescript-eslint/utils': ^8.41.0
    confusing-browser-globals: ^1.0.11
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-eslint-comments: ^3.2.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-markdown: ^5.1.0
    globals: ^16.3.0
    jsonc-eslint-parser: ^2.4.0
  test:
    '@types/react': ^19.1.12
    react: ^19.1.1
    vue: ^3.5.20

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
