packages:
  - packages/*
  - test

catalogs:
  dev:
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@commitlint/types': ^20.4.0
    '@lerna-lite/cli': ^4.11.2
    '@lerna-lite/publish': ^4.11.2
    '@types/confusing-browser-globals': ^1.0.3
    '@types/eslint': ^9.6.1
    '@types/node': ^25.2.2
    eslint: ^9.39.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    prettier: ^3.8.1
    rimraf: ^6.1.2
    sort-package-json: ^3.6.1
    taze: ^19.9.2
    tsdown: ^0.20.3
    tsx: ^4.21.0
    typescript: ^5.9.3
  peer:
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.0
    eslint-plugin-vue: ^10.7.0
    vue-eslint-parser: ^10.2.0
  prod:
    '@eslint/markdown': ^7.5.1
    '@typescript-eslint/eslint-plugin': ^8.54.0
    '@typescript-eslint/parser': ^8.54.0
    '@typescript-eslint/utils': ^8.54.0
    confusing-browser-globals: ^1.0.11
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-merge-processors: ^2.0.0
    eslint-plugin-eslint-comments: ^3.2.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsonc: ^2.21.1
    globals: ^17.3.0
    jsonc-eslint-parser: ^2.4.2
  test:
    '@types/react': ^19.2.13
    react: ^19.2.4
    vue: ^3.5.28

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
